version: "3.9"

services:
  db:
    container_name: todo_mysql_server
    image: mysql:latest
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
    - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpwd
      MYSQL_DATABASE: todo
      MYSQL_USER: todo
      MYSQL_PASSWORD: password
volumes:
  db_data: {}